apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-endringslogg
  namespace: teamfamilie
  labels:
    team: teamfamilie
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  image: {{ image }}
  prometheus:
    enabled: false
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: db-f1-micro
        databases:
          - envVarPrefix: db
            name: familie-endringslogg
  observability:
    autoInstrumentation:
      enabled: true
      runtime: "java"
    logging:
      destinations:
        - id: elastic
        - id: loki
  ingresses:
    - https://familie-endringslogg.intern.dev.nav.no
  replicas:
    min: 1
    max: 2
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-sak-frontend
        - application: familie-ba-sak-frontend
        - application: familie-ks-sak-frontend
        - application: familie-klage-frontend
        - application: familie-tilbake-frontend
        - application: tilleggsstonader-sak-frontend
          namespace: tilleggsstonader
        - application: saksbehandling
          namespace: aap
    outbound:
      external:
        - host: cdn.sanity.io
        - host: avzz8jwq.api.sanity.io
