apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-endringslogg
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - envVarPrefix: db
            name: familie-endringslogg
  ingresses:
    - https://familie-endringslogg.intern.nav.no
  accessPolicy:
    inbound:
      rules:
        - application: familie-ef-sak-frontend
        - application: familie-ba-sak-frontend
        - application: familie-ks-sak-frontend
        - application: familie-klage-frontend
        - application: familie-tilbake-frontend
