name: 'Remove Old Images'
on:
  workflow_dispatch:

jobs:
  remove-images:
    name: 'Remove old images job'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: 'familie-endringslogg'
          package-type: 'container'
          min-versions-to-keep: 10
